export enum SettingKey {
  GENERAL = 'GENERAL',
  BOOKING_RULES = 'BOOKING_RULES',
  BUS_AMENITIES = 'BUS_AMENITIES',
  PAYMENT_GATEWAYS = 'PAYMENT_GATEWAYS',
  BUS_TYPE_PRICING = 'BUS_TYPE_PRICING',
  PRICING_POLICIES = 'PRICING_POLICIES',
}
